table! {

    /// Representation of the `sys_email_registration` table.
    ///
    /// (Automatically generated by Diesel.)
    sys_email_registration (code) {
        /// The `code` column of the `sys_email_registration` table.
        ///
        /// Its SQL type is `Bpchar`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Bpchar,
        /// The `email` column of the `sys_email_registration` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `created_on` column of the `sys_email_registration` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_on -> Timestamptz,
    }
}

table! {

    /// Representation of the `sys_user` table.
    ///
    /// (Automatically generated by Diesel.)
    sys_user (id) {
        /// The `id` column of the `sys_user` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `active` column of the `sys_user` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        active -> Bool,
        /// The `username` column of the `sys_user` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Varchar,
        /// The `email` column of the `sys_user` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `password` column of the `sys_user` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Bytea,
        /// The `first_name` column of the `sys_user` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        first_name -> Varchar,
        /// The `last_name` column of the `sys_user` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        last_name -> Varchar,
        /// The `created_on` column of the `sys_user` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_on -> Timestamptz,
        /// The `updated_on` column of the `sys_user` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_on -> Timestamptz,
    }
}

allow_tables_to_appear_in_same_query!(
    sys_email_registration,
    sys_user,
);
